services:
  frontend:
    build:
      context: ./real-frontend
    ports:
      - "3001:3001"
    restart: always
    env_file: ./real-frontend/.env.local
    depends_on:
      - backend

  admin:
    build:
      context: ./realestate-admin
    ports:
      - "3000:3000"
    restart: always
    env_file: ./realestate-admin/.env.local
    depends_on:
      - backend

  backend:
    build:
      context: ./realestate-backend
    ports:
      - "4001:4001"
    restart: always
    env_file: ./realestate-backend/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: realestate-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
      - ./mongod.conf:/etc/mongo/mongod.conf
      - ./mongo-init:/docker-entrypoint-initdb.d
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
